### ISSUE TITLE
add location

### ISSUE THREAD

**Issue by Deepak-du** [Deepak-du/weather-app#1] opened 2020-10-10 03:57 UTC
Weather app is a simple app that shows you a weather. It comes with your standard features like your daily and hourly forecast along with access to additional information

**Comment by AbhinavGor** [comment] 2020-10-10 05:17
Assign it to me please @Deepak-du

**Comment by shrinish123** [comment] 2020-10-10 05:48
Hi, I am not able to understand what the issue is, please can you elaborate the issue

**Comment by aakashsoni-cloud** [comment] 2020-10-10 07:09
@Deepak-du  the request you have used for accessing the user location is wrong make it correct or open a new issue

**Closed as completed** 2020-10-10 12:15 UTC
Labels: hacktoberfest
